// <auto-generated />
using AstonMinimalAPIPostGre;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AstonMinimalAPIPostGre.Migrations
{
    [DbContext(typeof(MyApplicationDbContext))]
    [Migration("20221216192917_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("AstonMinimalAPIPostGre.Models.Item", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<string>("CategoryName_Item")
                        .HasColumnType("text");

                    b.Property<string>("Description_Item")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl_Item")
                        .HasColumnType("text");

                    b.Property<string>("Name_Item")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price_Item")
                        .HasColumnType("double precision");

                    b.HasKey("ItemId");

                    b.ToTable("items");
                });
#pragma warning restore 612, 618
        }
    }
}
